version: '3.6'

services: 
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: 'uvicorn backend.app:app --host 0.0.0.0  --reload --reload-dir backend --log-level debug'
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on: 
      - db
    
  db:
    image: postgres:13.3-alpine3.14
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - content_creator_vol:/var/lib/postgresql/data
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery --app=backend.worker worker --loglevel=info
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on: 
      - web
      - db
      - redis

  redis:
    image: redis:6.2.5-alpine3.14

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
volumes:
  content_creator_vol: